### ISSUE TITLE
Consider including WP Datepicker Styling

### ISSUE THREAD

**Issue by JJJ** [TheCraigHewitt/Seriously-Simple-Podcasting#132]
If you have a content security policy that doesn't allow inclusion of remote scripts, the Smoothness jQuery theme won't be accessible, and there is no local fallback.

<img width="988" alt="screen shot 2017-01-12 at 4 28 53 pm" src="https://cloud.githubusercontent.com/assets/88951/21911041/50aea862-d8e4-11e6-90af-4798f5f05e93.png">

Not ironically, I have a solution to this problem: https://github.com/stuttter/wp-datepicker-styling

I think it makes the most sense here to bundle styling that more closely matches `wp-admin` vs. relying on an external library.

**Comment by whyisjake** [comment]
So @JJJ, what are you proposing as the solution?

**Comment by JJJ** [comment]
Bundling and enqueing the CSS file from the above project, in place of the remote styling.

I meant to send a PR but ran out of time this afternoon.

**Comment by hlashbrooke** [comment]
FWIW I fully agree with this. I implemented the standard jQuery CSS there because it was quick to deploy. I still never liked the fact that the CSS wasn't in line with the rest of `wp-admin` though, so this would be a welcome improvement I think :)

**Comment by JJJ** [comment]
👍💜

**Comment by jonathanbossenger** [comment]
Fixed by #222 thanks @JJJ and @timnolte
