### ISSUE TITLE
Plugin conflict with WP Offload S3

### ISSUE THREAD

**Issue by klhall1987** [TheCraigHewitt/Seriously-Simple-Podcasting#149]
When I updated to the newest version of Seriously Simple Podcasting. It crashed my site and threw a fatal error. 

Here is a screenshot of the error:
<img width="1280" alt="screen shot 2017-05-16 at 8 56 23 pm" src="https://cloud.githubusercontent.com/assets/9393977/26134853/97fe99aa-3a7f-11e7-9a95-334650505241.png">

**Comment by whyisjake** [comment]
Looks like something to do with an s3 plugin.

**Comment by klhall1987** [comment]
Yea, my guess is there is a dependency conflict some where. I'm still trying to trace everything out.

**Comment by jonathanbossenger** [comment]
@klhall1987 do you use any other plugins that implement the AWS S3 SDK?

I'm in the process of implementing version 2 of the SDK to prevent conflicts with the version used by WP Offload to S3, if you are using another plugin that uses this SDK please let me know so that I can test that use case.

**Comment by klhall1987** [comment]
Hey @jonathanbossenger, 

Yes, It's WP Offload S3. The conflict is between SSP and WP Offload. I know a developer over at WP Offload, he sent me this documentation. I don't know if it will help you guys, but I thought it would share it with :) 

https://deliciousbrains.com/dependency-management-wordpress-proposal/#problem

Thanks,

Kenny
WP Ninjas, LLC

**Comment by jonathanbossenger** [comment]
Thanks Kenny, I actually spoke to Iain about it yesterday ;-)

Testing for 1.16.2 is currently underway, with WP Offload installed.

**Comment by jonathanbossenger** [comment]
This is fixed with #151
