### ISSUE TITLE
limit [podcast_playlist] to most recent X episodes

### ISSUE THREAD

**Issue by TheCraigHewitt** [TheCraigHewitt/Seriously-Simple-Podcasting#169]
currrently there's no way to limit the # of episodes in the [podcast_playlist] shortcode.  we could implement a limit parameter to only show the most recent X episodes on a rolling basis.

**Comment by simondowdles** [comment]
@TheCraigHewitt - I am going to commence this task, I do not foresee it being a biggie.

**Comment by TheCraigHewitt** [comment]
@simondowdles ok sounds good.  thanks.

**Comment by simondowdles** [comment]
I have implemented this and have a pull request open: https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/pull/175

Usage is as follows: [podcast_playlist series="on-life-software-development" limit="4"]
