### ISSUE TITLE
PHP issue > or >= 5.3.3 ?

### ISSUE THREAD

**Issue by TheCraigHewitt** [TheCraigHewitt/Seriously-Simple-Podcasting#172]
from wordpress.org support forum:

Looks like a simple enough fix. I modified the version check (line 23 of seriously-simple-podcasting.php) to use < instead of <= in the version_compare call. I assume your intent is that 5.3.3 is allowed, but 5.3.2 (and below) are not; you were excluding 5.3.3.

**Comment by jonathanbossenger** [comment]
Fixed by #173
