### ISSUE TITLE
Uploaded audio file does not play

### ISSUE THREAD

**Issue by jonathanbossenger** [TheCraigHewitt/Seriously-Simple-Podcasting#183]
Audio files are uploading, but do not play on the front end

**Comment by jonathanbossenger** [comment]
@TheCraigHewitt @simondowdles this seems to be related to a specific audio file I was testing, all other files seem fine, if you do any testing, please let me know if this reoccurs

**Comment by TheCraigHewitt** [comment]
worked for me.
