### ISSUE TITLE
Increase number of episodes in feed

### ISSUE THREAD

**Issue by nickv2002** [TheCraigHewitt/Seriously-Simple-Podcasting#214]
Based on the discussion in [an earlier question](https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/issues/135), I'm trying to increase the number of episodes on my feed by changing `wp-content/plugins/seriously-simple-podcasting/templates/feed-podcast.php` line 333 to

```
$num_posts = intval( apply_filters( 'ssp_feed_number_of_posts', get_option( 'posts_per_rss', 50 ) ) );
```
(the `50` on that line was originally `10`)

But when I delete my cache and check my feed after making that change I still only see 10 podcast episodes in the feed? I don't see `ssp_feed_number_of_posts` anywhere else other than the changelog. What am I doing wrong?

Thanks! for your help.
-Nick

**Comment by TheCraigHewitt** [comment]
@nickv2002 this is currently controlled by general WordPress settings for # of posts in a syndication feed.  Settings for this are in General -> Reading

It's been proposed previously to add this to some of the settings in Podcast -> Settings specifically for podcast related RSS feeds.  May be something to consider.

**Comment by nickv2002** [comment]
Thanks @TheCraigHewitt that did the trick.

I don't think you need a separate setting but maybe just a note/link in the Podcast Settings that this variable from regular Settings is connected.
