### ISSUE TITLE
Podcast tags are registered using the same name as WP's standard blog post tags

### ISSUE THREAD

**Issue by seriouspodcaster** [TheCraigHewitt/Seriously-Simple-Podcasting#218]
SSP's Podcast tag name - post_tag
WP's Blog Post tag name - post_tag

Fixing this would be as easy as renaming the SSP tag to something more unique, although any tags previously created will not show up after this.

**Comment by whyisjake** [comment]
Uhh, that's the point. Use the same table.

**Comment by seriouspodcaster** [comment]
@whyisjake We'd still be using the same table, just use a different taxonomy name, as we've had users complain that when clicking on a tag in their podcast, that their blog posts are also showing up in the list :)
