### ISSUE TITLE
Option to hide iTunes fields from episode meta

### ISSUE THREAD

**Issue by hlashbrooke** [TheCraigHewitt/Seriously-Simple-Podcasting#230]
If a podcaster is either not using iTunes entirely, or does not care about the extra meta fields that are available on each episode for iTunes, then those fields just make the episode meta UI a bit daunting. It would be great to have an option in the settings to hide those fields (just a CSS `display: none` would suffice to be honest) and then set intelligent defaults for them when the episode is saved.

It would make the UI more Seriously Simple :stuck_out_tongue:

**Comment by jonathanbossenger** [comment]
Fixed by #240
