### ISSUE TITLE
Load styles and scripts only when they are needed

### ISSUE THREAD

**Issue by goaround** [TheCraigHewitt/Seriously-Simple-Podcasting#266]
With the new version, all styles, scripts and fonts for the new HTML5 Player gets loaded on the frontend EVEN when I choose to stick with the Standard Compact Player. That are **17 additional server requests and 200kb** without any benefit for the user.

I would suggest to keep it "simple" and only load these scripts, styles & fonts if the new HTML5 Player is chosen as the media player. Additional I would only enqueue the scripts and styles if the media player is shown on the loaded page.

**Comment by goaround** [comment]
Hi,

I saw that some improvements where made. Only wavesurfer from the cloudflare CDN is still loading. Its at the html5_player_conditional_scripts function in includes/class-ssp-frontend.php but at the end of the file it will be enqueue anyway:

`add_action( 'wp_enqueue_scripts', 'ssp_enqueue_wave_surfer' );
function ssp_enqueue_wave_surfer(){
	wp_enqueue_script( 'ssp-wavesurfer', '//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.4.0/wavesurfer.min.js', SSP_VERSION, array( 'jquery' ) );
}`

**Comment by jonathanbossenger** [comment]
Fixed with #286 props @goaround 
Thanks
