### ISSUE TITLE
Text domain needed for localisation to be possible

### ISSUE THREAD

**Issue by hlashbrooke** [TheCraigHewitt/Seriously-Simple-Podcasting#289]
Wherever localisation functions are used (e.g. `__()`), you need to explicitly state the full text domain each time, otherwise the strings will not be translatable at all. Right now you are using variable placeholders like this:
```
$series_img_title = __( 'Series Image', $this->plugin_slug );
```

Those all need to be changed to this:
```
$series_img_title = __( 'Series Image', 'seriously-simple-podcasting' );
```

It looks like this is done throughout the plugin, so the issue isn't any one particular location.

**Comment by jonathanbossenger** [comment]
Fixed by #305
