### ISSUE TITLE
Error after updating to 1.19.13

### ISSUE THREAD

**Issue by bryanbartow** [TheCraigHewitt/Seriously-Simple-Podcasting#321]
I'm getting this error in my dashboard after updating the plugin:

`Notice: Undefined index: settings-updated in /nas/content/live/theyakkbryan/wp-content/plugins/seriously-simple-podcasting/includes/class-ssp-settings.php on line 169`

Anyone else?

**Comment by jonathanbossenger** [comment]
@bryanbartow could I ask you to go to the 1.19.14 branch, download the zip and try it on your site

https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/tree/release/1.19.14

Please let me know if this fixes the problem.

It shouldn't cause any issues, but to be safe, please make a backup of your site before installing it.

**Comment by jonathanbossenger** [comment]
OK thanks, I'll probably push this to the plugin repository tomorrow.
