### ISSUE TITLE
un expected change slug by translation

### ISSUE THREAD

**Issue by toiee-kameda** [TheCraigHewitt/Seriously-Simple-Podcasting#326]
A few month ago, someone committed Japanese translation. And this changed slug name from "podcast (default)" to "ポッドキャスト(japanese)". 

I used "ssp_archive_slug" filter for fixed this situation.

How should I do?

Ref: includes/class-ssp-admin.php
<img width="722" alt="2018-11-13 12 26 06" src="https://user-images.githubusercontent.com/7563975/48389254-fe49b780-e73f-11e8-81fb-d43b7264efdd.png">

---

by the way, this plugin is very simple and flexible. I use this for mobile learning in our university for our students. Thanks a lot!

**Comment by jonathanbossenger** [comment]
Hi @toiee-kameda I'm not sure if I understand your question, are you asking if this is the right way to fix it, or how to fix the incorrect translation.

If you want to help fix the incorrect translation you can do so on the plugin translation page - https://translate.wordpress.org/locale/ja/default/wp-plugins/seriously-simple-podcasting

I hope this helps?

**Comment by hlashbrooke** [comment]
The fix here would be to use [`_x()`](https://developer.wordpress.org/reference/functions/_x/) to localise the string as that allows you to provide a context for it so it can be different to other localisations of the same string in other contexts.
