### ISSUE TITLE
File size not showing after manually entered

### ISSUE THREAD

**Issue by RK905** [TheCraigHewitt/Seriously-Simple-Podcasting#336]
File size not showing after manually entered

**Comment by jonathanbossenger** [comment]
Hi @RK905 

In order to help me debug this issue, can you provide me with the following info:

1. What are you entering as the file size?
2. Where is it not displaying (I am assuming in the RSS Feed)?

Thanks

**Comment by JosephusPaye** [comment]
I just ran into a similar issue. It's in the RSS feed.

When the file size is manually entered for an episode using a link (not uploaded), [the check here](https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/blob/master/templates/feed-podcast.php#L393) fails, and the size is set to 1.

I also ran into a related problem where using uppercase size types, e.g. MB, GB, etc cause the [`convert_human_readable_to_bytes`](https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/blob/master/includes/ssp-functions.php#L523) function to fail.

PR incoming.
