### ISSUE TITLE
Where is wp_feed_number_of_posts filter?

### ISSUE THREAD

**Issue by JiveDig** [TheCraigHewitt/Seriously-Simple-Podcasting#339]
The docs https://support.castos.com/article/70-filter-reference reference a non-existent filter.
 Actually GitHub's related search pointed me to https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/issues/214 which showed me the filter is actually `ssp_feed_number_of_posts`, and where to find it. So you can close this, but it'd be worth updating your docs with the correct filter name. :)

**Comment by TheCraigHewitt** [comment]
@JiveDig thanks for the heads up on this. We're going to be implementing this as an option in the Podcast -> Settings -> Feed Details settings area here shortly but have updated the docs in the meantime.
