### ISSUE TITLE
SSP Series taxonomy overrides similar taxonomy provided by other plugins

### ISSUE THREAD

**Issue by mallardduck** [TheCraigHewitt/Seriously-Simple-Podcasting#340]
Due to having the SSP series taxonomy registered as `series` this plugin conflicts with others that bring in a series taxonomy as well. In my case I'm attempting to use `organize-seires`, however, I've tested and confirmed the issue with the `Series` plugin as well.

These plugins can be found here:
https://wordpress.org/plugins/series/
https://wordpress.org/plugins/organize-series/

For me, this is an issue as I want to take advantage of the more robust features offered by Organize Series for my traditional posts while utilizing the provided SSP series for only podcasts.

Out of the box we can control the slug, but not the taxonomy name that's being registered. If the registered taxonomy was unique to SSP then (in theory) we'd have everything needed to use SSP series for podcasts and another type for text posts.

I believe a minor change of updating this:

		register_taxonomy( 'series', $podcast_post_types, $series_args );

To:

		register_taxonomy( 'ssp-series', $podcast_post_types, $series_args );

...should be enough to improve plugin interoperbility while giving more control to end-users.

The biggest concern would be that this change would require the plugin to 'migrate' existing SSP series created to migrate to the new taxonomy name.

**Comment by mallardduck** [comment]
Another issue I encountered while trying to use SSP Series with a regular post is that they don't show up. So within my custom post type I can tell it to use `series` taxonomy which allows me to set them within a Series.

However, I cannot view the archive for this series as the Archives query doesn't know to include this post type. While I could add this CPT to being a podcast this is a purely text CPT so that doesn't feel too ideal.

Any suggestions or ideas would be much appreciated!

**Comment by eviolini** [comment]
@mallardduck it sounds like you want to see all podcasts from a series in an archive page, correct? If so you can try the snippets here https://support.castos.com/article/27-how-do-i-use-my-blog-categories-with-my-podcast-episodes

**Comment by mallardduck** [comment]
@eviolini that's not quite it.

What I'm reporting is a technical issue in how SSP creates the `series` taxonomy, how this affects plugins that provide a taxonomy by the same name and how this affects even non-podcast posts.

**Comment by jonathanbossenger** [comment]
@mallardduck thanks for logging the issue.

Just a quick note, it's not ideal to log two separate items as part of one issue, it makes it hard to keep track of both conversations. I know that the second item is also related to the series taxonomy, but i would consider it a separate issue. Could I ask you to log it separately and we can discuss the details of the problem there.

Getting back to your original item, I agree that it is frustrating when we use the same taxonomy name as another plugin. However as you've correctly pointed out, making a change like this would have far reaching consequences for our existing plugin users, and I'm not sure we're ready to implement such a sweeping change to the plugin at this time.

What I can suggest we implement is to add a filter to the registration of the series taxonomy, giving you more control over the taxonomy slug used to register the podcast series taxonomy.

So if we changed the taxonomy registration to 

`register_taxonomy( apply_filters( 'ssp_series_taxonomy', 'series' ), $podcast_post_types, $series_args );`

That would allow you to use the ssp_series_taxonomy filter to apply any specific series taxonomy you prefer, yet have no effect all on our existing plugin users.

**Comment by mallardduck** [comment]
@jonathanbossenger I believe that I only have a single issue that's appearing as multiple issues. Your suggested change would be enough to resolve my underlying issue. However I do suppose that some users may want to utilize the series taxonomy provided by SSP for posts - and in those cases, the archive issue I mentioned would be their main bug. I will create an issue for that use case.
