### ISSUE TITLE
Virtual URLs not detecting external MP3

### ISSUE THREAD

**Issue by cspenn** [TheCraigHewitt/Seriously-Simple-Podcasting#343]
Encountering an issue where SSP is creating virtual URLs to my MP3s that are not reflecting the external audio links.

![2019-01-31_13-38-55](https://user-images.githubusercontent.com/6747905/52076977-ea9f3780-255d-11e9-90fd-54b6b5fa9e71.png)

Live example on:
```https://www.trustinsights.ai/podcast```

**Comment by cspenn** [comment]
![2019-01-31_14-14-26](https://user-images.githubusercontent.com/6747905/52078976-8af75b00-2562-11e9-8560-1022b59df00b.png)

Example of back-end settings showing correct URLs.

**Comment by contemplate** [comment]
Same here.  It's causing the [ss_player] shortcode not to work with our external mp3 files.

**Comment by contemplate** [comment]
Actually I fixed it with this:
https://gist.github.com/hlashbrooke/51b5621b90010ccb8e15

**Comment by cspenn** [comment]
Thank you!
