### ISSUE TITLE
Error after updating to 1.19.19

### ISSUE THREAD

**Issue by bryanbartow** [TheCraigHewitt/Seriously-Simple-Podcasting#357]
I'm now getting the following error logged in my dashboard on a multisite install after updating to 1.19.19:

`Notice: Undefined variable: fields in /var/web/site/public_html/wp-content/plugins/seriously-simple-podcasting/includes/class-ssp-settings.php on line 1133`

**Comment by jonathanbossenger** [comment]
@bryanbartow thanks for bringing this to our attention, I've just pushed out 1.19.20 of the plugin to fix this, please update and confirm.

**Comment by bryanbartow** [comment]
@jonathanbossenger That fixed it. Thanks.
