### ISSUE TITLE
Cannot select Series when creating podcast from some "other" post types

### ISSUE THREAD

**Issue by lordneeko** [TheCraigHewitt/Seriously-Simple-Podcasting#361]
This is similar to #341 

When adding a “podcast” on the right hand side of my screen I have check boxes for telling it what series that podcast is apart of. However we have a post series type that existed before adding your podcast plugin which I want to continue using.

Your plugin allows me to tell it that I want this post type to also be in my podcast listing, and that works perfectly. However on that add post edit page, the widget that allows you to check the series to associate it with isn’t present. 

You can select a series for The Events Manager posts, standard WordPress posts, and of course SSP posts. But other plugins/themes which has a custom post type which doesn’t show the series.

**Comment by jonathanbossenger** [comment]
@lordneeko this should be fixed since the 1.20.2 release.

**Comment by lordneeko** [comment]
confirmed fixed
