### ISSUE TITLE
REST API Audio URL

### ISSUE THREAD

**Issue by bricedupuy** [TheCraigHewitt/Seriously-Simple-Podcasting#362]
Using
/wp-json/ssp/v1/episodes

In "meta" / "audio_file" Seriously Simple Podcasting returns the raw_audio_file_url 
instead of the of the download_link which would allow tracking 
ie ‘podcast-player’ or ‘podcast-download’

**Comment by jonathanbossenger** [comment]
Please update to 1.20.3 for this enhancement, details of the REST API addition in the changelog

**Comment by bricedupuy** [comment]
Thanks
