### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by nsoutter** [TheCraigHewitt/Seriously-Simple-Podcasting#366]
In your class-settings-controller.php file, on line 165, you create an array with the editor role.

Then on line 177 you attempt to add the "ssp_manage_podcast' cap to each role. 

However this assumes the wordpress default role "editor" exists. It can be removed (and we've done so).

Since we don't have an 'editor' role this causes a fatal crash and kills the back end.

I have rewritten the file to remove the need for an editor role, but on every update, the change is reverted.

I am hoping you can come up with a solution to this. I don't believe the plugin should require that role to function.

**Comment by jonathanbossenger** [comment]
Thanks @nsoutter

**Comment by jonathanbossenger** [comment]
Please update to 1.20.3 for this fix, thanks
