### ISSUE TITLE
Speakers Extension doesn't work with 1.20.2

### ISSUE THREAD

**Issue by dwerz** [TheCraigHewitt/Seriously-Simple-Podcasting#367]
With SSP 1.20.2 the speaker taxonomy disappeared from admin page.
No speaker column in the podcast list table. No more input possible.
Podcasts created with SSP < 1.20 still show a speaker in front end.
(WordPress: 5.2.1)

**Comment by jonathanbossenger** [comment]
Hi @dwerz thanks for bringing this to our attention.

**Comment by dwerz** [comment]
This problem was solved with the release of Seriously-Simple-Speakers 1.0.2, by submitting this commit: TheCraigHewitt/Seriously-Simple-Speakers@3810c2a
Thank you, Jonathan!

Note for other users:
The same solution - change of priority - brings back other taxonomies. For example, if someone has added **categories** to the podcast post type:
```
add_action( 'init', 'ssp_add_categories_to_podcast', 11);
Function ssp_add_categories_to_podcast () {
  register_taxonomy_for_object_type( 'category', 'podcast');
}
```
