### ISSUE TITLE
ss_podcast link_title="true" is failing

### ISSUE THREAD

**Issue by dwerz** [TheCraigHewitt/Seriously-Simple-Podcasting#368]
With SSP 1.20.2 link_title="true" in ss_podcast Shortcode doesn't work as documented.
I suspect the reason in ssp-functions.php line 196 + 224:
	`if ( true === $args['link_title'] ) ...`
The comparison operator '===' should be a '==', isn't it?

**Comment by jonathanbossenger** [comment]
Please update to 1.20.3 for this fix, thanks
