### ISSUE TITLE
RSS Feed "Author" vs "Owner"

### ISSUE THREAD

**Issue by OldItalian** [TheCraigHewitt/Seriously-Simple-Podcasting#372]
I noticed yesterday when I was making sure iTunes was still recognizing our podcast that iTunes (and I expect other podcast distributers) recognize the "Author" of the podcast episode as the Wordpress account that posted the episode. The podcast "Owner" recognizes correctly for the series owner/creator.

My issue is that we use our website for more than just podcasting, and the same person is not necessarily posting the episodes, so the "Author" is always different (and it's weird to see user names associated with something like this).

It looks like the feed-podcast.php doesn't have any override for listing the "Author" as the "Owner" and the author will always be dictated by the poster username. Is this intended? It'd be great if either the owner = the author or have some way to choose a global author.

**Comment by jonathanbossenger** [comment]
Hi @OldItalian 

The Author field set in the Feed settings is applied to the author field for the overall feed. However on a per episode basis, you are correct, the display name of the user who created the post is used for the itunes:author field.

There are currently two options available to you to change this. One is to change the "Display name publicly as" field in your WordPress User Profile. The other is a filter available that you can use to override this. If you're comfortable with adding a PHP snippet to your site, you can do something like this:

https://gist.github.com/jonathanbossenger/381ffea8e2577de4eb1f19f48373dc51

**Comment by OldItalian** [comment]
Thanks @jonathanbossenger! Just got a chance to try it out. It works like a charm. I appreciate the help.
