### ISSUE TITLE
content:encoded no longer in RSS feeds

### ISSUE THREAD

**Issue by samkuhn** [TheCraigHewitt/Seriously-Simple-Podcasting#383]
Our iOS / Android apps rely on content:encoded to display full html episode descriptions to our users. In the latest version these are no longer available in any of our feeds even with Turbocharge off.

[Example feed](https://radio.amicus-curiae.net/feed/podcast/angle-droit)

We don't mind switching to another tag if needed so long as it is a full html episode description without cropping since cropped html is a cause of rendering bugs on our side.

**Comment by jonathanbossenger** [comment]
This has been fixed in version 1.20.6 of the plugin

**Comment by samkuhn** [comment]
I can confirm that content:encoded is indeed working again with the latest version. Thanks for the speedy fix!

**Comment by jonathanbossenger** [comment]
@samkuhn thank you for following up and confirming
