### ISSUE TITLE
Scripts and styles for HTML5 player showing up in footer even when standard player is selected

### ISSUE THREAD

**Issue by rghedin** [TheCraigHewitt/Seriously-Simple-Podcasting#401]
When the standard compact player is chosen, the following files are loaded in footer regardless:

```
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:400,700&v=1.20.9"/>
<link rel="stylesheet" href="https://manualdousuario.net/wp-content/plugins/seriously-simple-podcasting/assets/css/icon_fonts.css?v=1.20.9"/>
<link rel="stylesheet" href="https://manualdousuario.net/wp-content/plugins/seriously-simple-podcasting/assets/fonts/Gizmo/gizmo.css?v=1.20.9"/>
<link rel="stylesheet" href="https://manualdousuario.net/wp-content/plugins/seriously-simple-podcasting/assets/css/frontend.css?v=1.20.9"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.4.0/wavesurfer.min.js?v=1.20.9"></script>
```

Can't say why or if it's something related to my WordPress install.

**Comment by jonathanbossenger** [comment]
Thanks @rghedin I'm going to post the temporary fixes here, until we can resolve this

global $ss_podcasting;
remove_action( 'wp_print_footer_scripts', array( $ss_podcasting, 'html5_player_conditional_scripts' ) );
remove_action( 'wp_print_footer_scripts', array( $ss_podcasting, 'html5_player_styles' ) );
remove_action( 'wp_enqueue_scripts', array( $ss_podcasting, 'load_scripts' ) );
remove_action( 'wp_footer', array( $ss_podcasting, 'ssp_override_player_styles' ) );

This will remove all HTML player scripts and styles, until we can find and resolve this bug. 

Thanks for reporting it.

**Comment by Brugman** [comment]
I think I can PR this soon. (Hacktoberfesting)
