### ISSUE TITLE
Add filters to disable get_file_duration and get_file_size functionality programatically

### ISSUE THREAD

**Issue by jonathanbossenger** [TheCraigHewitt/Seriously-Simple-Podcasting#420]
If audio files are not hosted somewhere that the file data can be read, this automatic functionality can cause breaking errors. Adding get_file_duration_enabled and get_file_size_enabled filters to the above mentioned functions will allow site owners to disable this functionality.

**Comment by SecondLineThemes** [comment]
+1

We've seen multiple sites that crashed due to this issue, using multiple non-Castos hosts. 
The problematic episodes were typically >70MB.

Would be nice to have a fallback or simply return false instead of crashing.

**Comment by jonathanbossenger** [comment]
@SecondLineThemes 

version 1.20.11 of the plugin shipped today, which includes two new filters ssp_enable_get_file_duration and ssp_enable_get_file_size. If you return false to these filters, they will disable the default get_file_duration and get_file_size functionality, for externally hosted files.

**Comment by SecondLineThemes** [comment]
@jonathanbossenger 

Thanks! That's a great addition as we've seen a handful of websites crash because of this.

It could be interesting to try and find a way and prevent these two functions from timing out in the future, by default, but it's a great solution for the time being.
