### ISSUE TITLE
Various bugfixes are stuck in features/hacktoberfest

### ISSUE THREAD

**Issue by theGrue** [TheCraigHewitt/Seriously-Simple-Podcasting#424]
I've been watching for #336 to be fixed for almost an entire year, and it seems like we're so close! For some reason this fix and a bunch of others were merged to `feature/hacktoberfest` instead of  `master` or `release/` or whatever your strategy is. What's the plan for all the fixes in this branch? Should I just open a PR?

**Comment by jonathanbossenger** [comment]
Hi @theGrue we've had a plugin update scheduled for some time now (back since just after Hacktoberfest) we just got delayed/distracted with other more pressing matters. 

I'll be running final tests this week to prepare for a pre holiday update. Please bear with me.

Thanks
