### ISSUE TITLE
Permalink of series are broken when using the ssp_feed_slug filter

### ISSUE THREAD

**Issue by maartenhunink** [TheCraigHewitt/Seriously-Simple-Podcasting#440]
When you use the `ssp_feed_slug` filter to change the slug of a feed, the general rss feed will work with the new feed url, but all rss feeds from series will be broken and show the following error:

`wp_die WordPress &amp;rsaquo; Error ERROR: This is not a valid feed template. 404`

1. Add the folowing code in functions.php to change the feed slug

```
add_filter( 'ssp_feed_slug', 'ssp_modify_podcast_feed_slug' );
function ssp_modify_podcast_feed_slug ( $slug ) {
  return 'audio';
}
```
2. Re-save your permalinks
3. Make sure you have a serie
4. Visit the new feed url of the serie

**Comment by jonathanbossenger** [comment]
This has been fixed in the 2.0.0 release
