### ISSUE TITLE
Php notices when attaching podcasts to a custom post type

### ISSUE THREAD

**Issue by maartenhunink** [TheCraigHewitt/Seriously-Simple-Podcasting#444]
After attaching podcasts to a custom post type, the following php notices appear:

```
Notice: Undefined index: meta in /test/wp-content/plugins/seriously-simple-podcasting/php/classes/rest/class-rest-api-controller.php on line 265

Notice: Trying to access array offset on value of type null in /test/wp-content/plugins/seriously-simple-podcasting/php/classes/rest/class-rest-api-controller.php on line 265
```

**How To Reproduce**
1. Make sure `define( 'WP_DEBUG', true );` is set in wp-config.php
2. Create a custom post type
3. Select that post type as a 'Podcast post type'
4. Add a new item of that post type
5. See error

**Comment by jonathanbossenger** [comment]
This has been fixed in the 2.0.0 release
