### ISSUE TITLE
Bulk import functions

### ISSUE THREAD

**Issue by hlashbrooke** [TheCraigHewitt/Seriously-Simple-Podcasting#80]
This will work best as an extension, but we need to have a bulk import option that allows for the following things:
- [ ] Import from any podcast RSS feed
- [ ] Import from other podcasting plugins (Blubrry, etc.)
- [ ] Import from CSV (less important and more complex, but would be good to include)

**Comment by whyisjake** [comment]
I actually wrote this code as part of a CLI script. Lemme dig it up.

**Comment by hlashbrooke** [comment]
That would be great to have a look at - thanks!

**Comment by whyisjake** [comment]
Started a PR over at #81 that we used at WIRED to import old feeds to SSP. It takes an RSS feed, and tries to match up those episodes to old posts, and then create them if needed.

**Comment by hlashbrooke** [comment]
That sounds perfect - I'll have a look through it :)
